apiVersion: v1
kind: Namespace
metadata:
  name: nginxnamespace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: nginxnamespace
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginxnamespace
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.8
        resources:
          limits:
            memory: 128Mi
            cpu: 250m
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: volume
      volumes:
       - name: volume
         persistentVolumeClaim:
          claimName: nginx-pvc
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: nginxnamespace
  name: nginx
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 30 # target CPU utilization
  
---

kind: Service
apiVersion: v1
metadata:
  name:  nginx
  namespace: nginxnamespace
spec:
  selector:
    app: nginx
  type:  LoadBalancer
  ports:
  - port:  80
    targetPort:  80
